
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 30 21:04:07 CET 2016
//----------------------------------------------------

package MIPS;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_CERRADO = 11;
  public static final int UMINUS = 12;
  public static final int SUMA = 8;
  public static final int PUNTO_COMA = 4;
  public static final int PAR_ABIERTO = 10;
  public static final int MOSTRAR = 3;
  public static final int MULTIPLICACION = 6;
  public static final int EOF = 0;
  public static final int LEER = 2;
  public static final int error = 1;
  public static final int ASIGNACION = 5;
  public static final int DIVISION = 7;
  public static final int RESTA = 9;
  public static final int VARIABLE_VALIDA = 13;
  public static final int INTEGER_LITERAL = 14;
}

